# Generated by Django 5.2.5 on 2025-08-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('origin_airport', models.CharField(max_length=255)),
                ('destination_airport', models.CharField(max_length=255)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('number_of_adults', models.PositiveSmallIntegerField(default=1)),
                ('number_of_children', models.PositiveSmallIntegerField(default=0)),
                ('number_of_infants_in_seat', models.PositiveSmallIntegerField(default=0)),
                ('number_of_infants_on_lap', models.PositiveSmallIntegerField(default=0)),
                ('cabin_class', models.CharField(default='ECONOMY', max_length=255)),
                ('device', models.GenericIPAddressField()),
                ('search_results', models.JSONField()),
            ],
        ),
    ]
