# Generated by Django 5.2.5 on 2025-08-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsearch',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail')], default='FAIL', help_text='The outcome of the search operation.', max_length=10),
        ),
    ]
