# Generated by Django 5.2.5 on 2025-08-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_flightsearch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsearch',
            name='currency',
            field=models.CharField(default='USD', max_length=255),
        ),
    ]
